grails-app/domain/grailsblog/Category.groovy
package grailsblog

class Category {
    def slugGeneratorService

    String name
    String slug = ""
    Date dateCreated
    Date lastUpdated

    static constraints = {
        name blank: false, nullable: false, unique: true
    }

    Set<Post> getPosts() {
        PostCategory.findAllByCategory(this).collect { it.post } as Set
    }

    def beforeInsert() {
        this.slug = slugGeneratorService.generateSlug(this.class, "slug", name, true)
    }

    def beforeUpdate() {
        if (isDirty('name')) {
            this.slug = slugGeneratorService.generateSlug(this.class, "slug", name, true)
        }
    }
}

grails-app/controllers/grailsblog/CategoryController.groovy
package grailsblog



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class CategoryController {

    static allowedMethods = [save: "POST", update: "PUT"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Category.list(params), model:[categoryInstanceCount: Category.count()]
    }

    def create() {
        respond new Category(params)
    }

    @Transactional
    def save(Category categoryInstance) {
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'create'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'categoryInstance.label', default: 'Category'), categoryInstance.name])
                redirect action:"index", method:"GET"
            }
            '*' { respond categoryInstance, [status: CREATED] }
        }
    }

    def edit(Category categoryInstance) {
        respond categoryInstance
    }

    @Transactional
    def update(Category categoryInstance) {
        if (categoryInstance == null) {
            notFound()
            return
        }

        if (categoryInstance.hasErrors()) {
            respond categoryInstance.errors, view:'edit'
            return
        }

        categoryInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.name])
                redirect action: "index", method: "GET"
            }
            '*'{ respond categoryInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Category categoryInstance) {

        if (categoryInstance == null) {
            notFound()
            return
        }

        PostCategory.removeAll(categoryInstance)

        categoryInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Category.label', default: 'Category'), categoryInstance.name])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def list(String slug) {
        def category = Category.findBySlug(slug)

        if (category == null) {
            notFound()
            return
        }

        def postInstaceList = category.getPosts()

        respond postInstaceList, model:[categories: Category.findAll(), tags: Tag.findAll(), categoryInstance: category, postInstaceList: postInstaceList]
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'categoryInstance.label', default: 'Category'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/category/_form.gsp
<%@ page import="grailsblog.Category" %>

<div class="form-group">
    <label for="name">Category Name <span class="required-indicator">*</span></label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Enter category name" value="${categoryInstance?.name}" required="">
</div>

<div class="form-group">
    <g:if test="${categoryInstance.id}">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Update category
        </button>
        or
        <a href="${ createLink(controller: 'category', action: 'delete', id: categoryInstance.id) }" class="btn btn-danger" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
            <i class="fa fa-trash-o"></i> Delete category
        </a>
    </g:if>
    <g:else>
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Create category
        </button>
    </g:else>
    or
    <a href="${ createLink(controller: 'category', action: 'index') }">Cancel</a>
</div>

grails-app/views/category/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Create a new category</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Create a new category</h1>

                <ol class="breadcrumb">
                    <li>
                        <g:link class="list" action="index">
                            <i class="fa fa-list-ul"></i> Categories
                        </g:link>
                    </li>
                    <li class="active">
                        Create a new category
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <g:hasErrors bean="${categoryInstance}">
                    <g:eachError bean="${categoryInstance}" var="error">
                        <div class="alert alert-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
                            <g:message error="${error}"/>
                        </div>
                    </g:eachError>
                </g:hasErrors>

                <g:form url="[resource:categoryInstance, action:'save']" >
                    <g:render template="form"/>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/category/edit.gsp
<%@ page import="grailsblog.Category" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Edit category ${categoryInstance.name}</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Edit user ${categoryInstance.name}</h1>

                <ol class="breadcrumb">
                    <li>
                        <g:link class="list" action="index">
                            <i class="fa fa-list-ul"></i> Categories
                        </g:link>
                    </li>
                    <li class="active">
                        Edit user ${categoryInstance.name}
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <g:hasErrors bean="${categoryInstance}">
                    <g:eachError bean="${categoryInstance}" var="error">
                        <div class="alert alert-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
                            <g:message error="${error}"/>
                        </div>
                    </g:eachError>
                </g:hasErrors>

                <g:form url="[resource:categoryInstance, action:'update']" method="PUT" >
                    <g:render template="form"/>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/category/index.gsp
<%@ page import="grailsblog.Category" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Categories</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Categories</h1>

                <ol class="breadcrumb">
                    <li class="active">
                        <i class="fa fa-list-ul"></i> Categories
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <p>
                    <a href="${ createLink(action: 'create') }" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Create a new category
                    </a>
                </p>

                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Category Name</th>
                                <th>Slug</th>
                            </tr>
                        </thead>
                        <tbody>
                            <g:each in="${categoryInstanceList}" status="i" var="categoryInstance">
                                <tr>
                                    <td>
                                        <g:link action="edit" id="${categoryInstance.id}">
                                            ${categoryInstance.name}
                                        </g:link>
                                    </td>
                                    <td>
                                        ${categoryInstance.slug}
                                    </td>
                                </tr>
                            </g:each>
                            <g:unless test="${categoryInstanceList}">
                                <tr>
                                    <td colspan="2">
                                        <p class="noRecord">No Categories Found!</p>
                                    </td>
                                </tr>
                            </g:unless>
                        </tbody>
                    </table>
                </div>

                <div class="pagination">
                    <g:paginate total="${categoryInstanceCount ?: 0}" controller="category" action="index" />
                </div>
            </div>
        </div>
    </body>
</html>

grails-app/views/category/list.gsp
<%@ page import="grailsblog.Category" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <title>Grailsblog - ${categoryInstance.name}</title>
    </head>
    <body>
        <g:each in="${categoryInstance.getPosts()}" status="i" var="postInstance">
            <article class="post_article">
                <h3 class="post_title">
                    <g:link controller="post" action="show" params="[slug: postInstance.slug]">
                        ${ postInstance.title }
                    </g:link>
                </h3>
                <h6 class="post_date">
                     Posted on <g:formatDate format="MMMMM d, yyyy" date="${ postInstance.dateCreated }" />
                </h6>

                <div class="post_content">
                    ${ raw(postInstance.content) }
                </div>

                <div class="post_meta_info">
                    <p>Posted by: ${ postInstance.author.fullname }</p>
                    <p>
                        Category:
                        <g:each in="${postInstance.getCategories()}" status="cat_i" var="postCategory">
                            <g:link controller="category" action="list" params="[slug: postCategory.slug]">${postCategory.name}</g:link>${ (postInstance.getCategories().size() != (cat_i + 1) ) ? ', ' : ''}
                        </g:each>
                    </p>
                    <p>
                        Tags:
                        <g:each in="${postInstance.getTags()}" status="tag_i" var="postTag">
                            <g:link controller="tag" action="list" params="[slug: postTag.slug]">${postTag.name}</g:link>${ (postInstance.getTags().size() != (tag_i + 1) ) ? ', ' : ''}
                        </g:each>
                    </p>
                </div>
            </article>

            <g:if test="${categoryInstance.getPosts().size() != (i+1)}">
                <hr>
                <br>
            </g:if>
        </g:each>

        <g:if test="${categoryInstance.getPosts() == 0}">
            <h2>No posts found for the category ${ categoryInstance.name }</h2>
        </g:if>
    </body>
</html>