grails-app/domain/grailsblog/Tag.groovy
package grailsblog

class Tag {
    def slugGeneratorService

    String name
    String slug = ""
    Date dateCreated
    Date lastUpdated

    static constraints = {
        name blank: false, nullable: false, unique: true
    }

    Set<Post> getPosts() {
        PostTag.findAllByTag(this).collect { it.post } as Set
    }

    def beforeInsert() {
        this.slug = slugGeneratorService.generateSlug(this.class, "slug", name, true)
    }

    def beforeUpdate() {
        if (isDirty('name')) {
            this.slug = slugGeneratorService.generateSlug(this.class, "slug", name, true)
        }
    }
}

grails-app/controllers/grailsblog/TagController.groovy
package grailsblog



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class TagController {

    static allowedMethods = [save: "POST", update: "PUT"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Tag.list(params), model:[tagInstanceCount: Tag.count()]
    }

    def create() {
        respond new Tag(params)
    }

    @Transactional
    def save(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'create'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'tagInstance.label', default: 'Tag'), tagInstance.name])
                redirect action: "index", method: "GET"
            }
            '*' { respond tagInstance, [status: CREATED] }
        }
    }

    def edit(Tag tagInstance) {
        respond tagInstance
    }

    @Transactional
    def update(Tag tagInstance) {
        if (tagInstance == null) {
            notFound()
            return
        }

        if (tagInstance.hasErrors()) {
            respond tagInstance.errors, view:'edit'
            return
        }

        tagInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.name])
                redirect action: "index", method: "GET"
            }
            '*'{ respond tagInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Tag tagInstance) {

        if (tagInstance == null) {
            notFound()
            return
        }

        PostTag.removeAll(tagInstance)

        tagInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Tag.label', default: 'Tag'), tagInstance.name])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def list(String slug) {
        def tag = Tag.findBySlug(slug)

        if (tag == null) {
            notFound()
            return
        }

        def postInstaceList = tag.getPosts()

        respond postInstaceList, model:[categories: Category.findAll(), tags: Tag.findAll(), tagInstance: tag, postInstaceList: postInstaceList]
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'tagInstance.label', default: 'Tag'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/tag/_form.gsp
<%@ page import="grailsblog.Tag" %>

<div class="form-group">
    <label for="name">Tag Name <span class="required-indicator">*</span></label>
    <input type="text" class="form-control" id="name" name="name" placeholder="Enter tag name" value="${tagInstance?.name}" required="">
</div>

<div class="form-group">
    <g:if test="${tagInstance.id}">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Update tag
        </button>
        or
        <a href="${ createLink(controller: 'tag', action: 'delete', id: tagInstance.id) }" class="btn btn-danger" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
            <i class="fa fa-trash-o"></i> Delete tag
        </a>
    </g:if>
    <g:else>
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Create tag
        </button>
    </g:else>
    or
    <a href="${ createLink(controller: 'tag', action: 'index') }">Cancel</a>
</div>

grails-app/views/tag/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Create a new tag</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Create a new tag</h1>

                <ol class="breadcrumb">
                    <li>
                        <g:link class="list" action="index">
                            <i class="fa fa-list-ul"></i> Tags
                        </g:link>
                    </li>
                    <li class="active">
                        Create a new tag
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <g:hasErrors bean="${tagInstance}">
                    <g:eachError bean="${tagInstance}" var="error">
                        <div class="alert alert-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
                            <g:message error="${error}"/>
                        </div>
                    </g:eachError>
                </g:hasErrors>

                <g:form url="[resource:tagInstance, action:'save']" >
                    <g:render template="form"/>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/tag/edit.gsp
<%@ page import="grailsblog.Tag" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Edit tag ${tagInstance.name}</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Edit tag ${tagInstance.name}</h1>

                <ol class="breadcrumb">
                    <li>
                        <g:link class="list" action="index">
                            <i class="fa fa-list-ul"></i> Categories
                        </g:link>
                    </li>
                    <li class="active">
                        Edit user ${tagInstance.name}
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <g:hasErrors bean="${tagInstance}">
                    <g:eachError bean="${tagInstance}" var="error">
                        <div class="alert alert-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
                            <g:message error="${error}"/>
                        </div>
                    </g:eachError>
                </g:hasErrors>

                <g:form url="[resource:tagInstance, action:'update']" method="PUT" >
                    <g:render template="form"/>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/tag/index.gsp
<%@ page import="grailsblog.Tag" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Tags</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Tags</h1>

                <ol class="breadcrumb">
                    <li class="active">
                        <i class="fa fa-list-ul"></i> Tags
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <p>
                    <a href="${ createLink(action: 'create') }" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Create a new tag
                    </a>
                </p>

                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Tag Name</th>
                                <th>Slug</th>
                            </tr>
                        </thead>
                        <tbody>
                            <g:each in="${tagInstanceList}" status="i" var="tagInstance">
                                <tr>
                                    <td>
                                        <g:link action="edit" id="${tagInstance.id}">
                                            ${tagInstance.name}
                                        </g:link>
                                    </td>
                                    <td>
                                        ${tagInstance.slug}
                                    </td>
                                </tr>
                            </g:each>
                            <g:unless test="${tagInstanceList}">
                                <tr>
                                    <td colspan="2">
                                        <p class="noRecord">No Tags Found!</p>
                                    </td>
                                </tr>
                            </g:unless>
                        </tbody>
                    </table>
                </div>

                <div class="pagination">
                    <g:paginate total="${tagInstanceCount ?: 0}" controller="tag" action="index" />
                </div>
            </div>
        </div>
    </body>
</html>

grails-app/views/tag/list.gsp
<%@ page import="grailsblog.Tag" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <title>Grailsblog - ${tagInstance.name}</title>
    </head>
    <body>
        <g:each in="${tagInstance.getPosts()}" status="i" var="postInstance">
            <article class="post_article">
                <h3 class="post_title">
                    <g:link controller="post" action="show" params="[slug: postInstance.slug]">
                        ${ postInstance.title }
                    </g:link>
                </h3>
                <h6 class="post_date">
                     Posted on <g:formatDate format="MMMMM d, yyyy" date="${ postInstance.dateCreated }" />
                </h6>

                <div class="post_content">
                    ${ raw(postInstance.content) }
                </div>

                <div class="post_meta_info">
                    <p>Posted by: ${ postInstance.author.fullname }</p>
                    <p>
                        Category:
                        <g:each in="${postInstance.getCategories()}" status="cat_i" var="postCategory">
                            <g:link controller="category" action="list" params="[slug: postCategory.slug]">${postCategory.name}</g:link>${ (postInstance.getCategories().size() != (cat_i + 1) ) ? ', ' : ''}
                        </g:each>
                    </p>
                    <p>
                        Tags:
                        <g:each in="${postInstance.getTags()}" status="tag_i" var="postTag">
                            <g:link controller="tag" action="list" params="[slug: postTag.slug]">${postTag.name}</g:link>${ (postInstance.getTags().size() != (tag_i + 1) ) ? ', ' : ''}
                        </g:each>
                    </p>
                </div>
            </article>

            <g:if test="${tagInstance.getPosts().size() != (i+1)}">
                <hr>
                <br>
            </g:if>
        </g:each>

        <g:if test="${tagInstance.getPosts() == 0}">
            <h2>No posts found for the category ${ tagInstance.name }</h2>
        </g:if>
    </body>
</html>