grails-app/domain/grailsblog/Post.groovy
package grailsblog

class Post {
    def slugGeneratorService

    String title
    String slug = ""
    String content
    Date dateCreated
    Date lastUpdated

    static belongsTo = [author: SecUser]

    static hasMany = [comments: Comment]

    static constraints = {
        title blank: false, nullable: false
        content blank: false, nullable: false, type: 'text'
    }

    static mapping = {
        content sqlType: 'text'
    }

    Set<Category> getCategories() {
        PostCategory.findAllByPost(this).collect { it.category } as Set
    }

    Set<Tag> getTags() {
        PostTag.findAllByPost(this).collect { it.tag } as Set
    }

    def beforeInsert() {
        this.slug = slugGeneratorService.generateSlug(this.class, "slug", title, true)
    }

    def beforeUpdate() {
        if (isDirty('title')) {
            this.slug = slugGeneratorService.generateSlug(this.class, "slug", title, true)
        }
    }
}

grails-app/controllers/grailsblog/PostController.groovy
package grailsblog



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PostController {
    def springSecurityService

    static allowedMethods = [save: "POST", update: "PUT"]

    def index(Integer max) {
        def currentUser = springSecurityService.getCurrentUser()
        def adminRole = SecRole.findByAuthority('ROLE_ADMIN')

        params.max = Math.min(max ?: 10, 100)

        def posts = Post.list(params)
        def postsCount = 0

        if (!currentUser.authorities.contains(adminRole)) {
            posts = Post.findAllByAuthor(currentUser)
            postsCount = Post.countByAuthor(currentUser)
        } else {
            postsCount = Post.count()
        }

        respond posts, model:[postInstanceCount: postsCount]
    }

    def create() {
        respond new Post(params), model:[currentUser: springSecurityService.getCurrentUser(), categories: Category.findAll(), tags: Tag.findAll()]
    }

    @Transactional
    def save(Post postInstance) {
        if (postInstance == null) {
            notFound()
            return
        }

        if (postInstance.hasErrors()) {
            respond postInstance.errors, view:'create'
            return
        }

        postInstance.save flush:true

        associatePostsWithCategories(postInstance, params.list("categories"))
        associatePostsWithTags(postInstance, params.list("tags"))

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'postInstance.label', default: 'Post'), postInstance.title])
                redirect action: "index", method: "GET"
            }
            '*' { respond postInstance, [status: CREATED] }
        }
    }

    def edit(Post postInstance) {
        respond postInstance, model:[categories: Category.findAll(), tags: Tag.findAll()]
    }

    @Transactional
    def update(Post postInstance) {
        if (postInstance == null) {
            notFound()
            return
        }

        if (postInstance.hasErrors()) {
            respond postInstance.errors, view:'edit'
            return
        }

        postInstance.save flush:true

        associatePostsWithCategories(postInstance, params.list("categories"))
        associatePostsWithTags(postInstance, params.list("tags"))

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Post.label', default: 'Post'), postInstance.title])
                redirect action: "index", method: "GET"
            }
            '*'{ respond postInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Post postInstance) {

        if (postInstance == null) {
            notFound()
            return
        }

        PostCategory.removeAll(postInstance)
        PostTag.removeAll(postInstance)

        postInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Post.label', default: 'Post'), postInstance.title])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        params.sort = "dateCreated"
        params.order = "desc"

        respond Post.list(params), model:[postInstanceCount: Post.count(), categories: Category.findAll(), tags: Tag.findAll()]
    }

    def show(String slug) {
        def postInstance = Post.findBySlug(slug)

        if (postInstance == null) {
            notFound()
            return
        }

        respond postInstance, model:[categories: Category.findAll(), tags: Tag.findAll()]
    }

    protected void associatePostsWithTags(Post post, tags) {
        def tag

        PostTag.removeAll(post)

        tags.each() {
            tag = Tag.findByName(it) ?: new Tag(name: it).save(failOnError: true)

            if (!post.tags.contains(tag)) {
               PostTag.create post, tag
            }
        }
    }

    protected void associatePostsWithCategories(Post post, categories) {
        def category

        PostCategory.removeAll(post)

        categories.each() {
            category = Category.findByName(it) ?: new Category(name: it).save(failOnError: true)

            if (!post.categories.contains(category)) {
               PostCategory.create post, category
            }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'postInstance.label', default: 'Post'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/post/_form.gsp
<%@ page import="grailsblog.Post" %>
<div class="form-group">
    <label for="title">Title <span class="required-indicator">*</span></label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Enter post title" value="${postInstance?.title}" required="">
</div>

<hr>

<div class="form-group">
    <label for="categories">Categories</label>
    <select id="categories" name="categories" multiple data-placeholder="Choose categories" class="chosen-select form-control chosen-create-entry">
        <g:each in="${categories}" status="i" var="category">
        <g:if test="${postInstance.id}">
            <option value="${category.name}" <g:if test="${postInstance.categories.contains(category)}">selected="selected"</g:if>>${category.name}</option>
        </g:if>
        <g:else>
            <option value="${category.name}">${category.name}</option>
        </g:else>
        </g:each>
    </select>
</div>

<div class="form-group">
    <label for="tags">Tags</label>
    <select id="tags" name="tags" multiple data-placeholder="Choose tags" class="chosen-select form-control chosen-create-entry">
        <g:each in="${tags}" status="i" var="tag">
        <g:if test="${postInstance.id}">
            <option value="${tag.name}" <g:if test="${postInstance.tags.contains(tag)}">selected="selected"</g:if>>${tag.name}</option>
        </g:if>
        <g:else>
            <option value="${tag.name}">${tag.name}</option>
        </g:else>
        </g:each>
    </select>
</div>

<hr>
<textarea id="content" name="content" class="tinymce-editor">${postInstance?.content}</textarea>
<hr>

<div class="form-group">
    <g:if test="${postInstance.id}">
        <input type="hidden" name="author" value="${postInstance?.author.id}">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Update post
        </button>
        or
        <a href="${ createLink(controller: 'post', action: 'delete', id: postInstance.id) }" class="btn btn-danger" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
            <i class="fa fa-trash-o"></i> Delete post
        </a>
    </g:if>
    <g:else>
        <input type="hidden" name="author" value="${currentUser.id}">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Create post
        </button>
    </g:else>
    or
    <a href="${ createLink(controller: 'post', action: 'index') }">Cancel</a>
</div>

<script type="text/javascript">
    jQuery("#categories").chosen({no_results_text: "Hit ENTER to create a new category:"});
    jQuery("#tags").chosen({no_results_text: "Hit ENTER to create a new tag:"});

    tinymce.init({
        selector: "textarea.tinymce-editor",
        height: 400,
        encoding: "raw",
        plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table contextmenu paste"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
    });
</script>

grails-app/views/post/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Create a new post</title>

        <link rel="stylesheet" href="${resource(dir: 'css', file: 'chosen.css')}" type="text/css">

        <script type="text/javascript" src="${resource(dir: 'js/tinymce/', file: 'tinymce.min.js')}"></script>
        <script src="${resource(dir: 'js', file: 'chosen.jquery.js')}"></script>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Create a new post</h1>

                <ol class="breadcrumb">
                    <li>
                        <g:link class="list" action="index">
                            <i class="fa fa-files-o"></i> Posts
                        </g:link>
                    </li>
                    <li class="active">
                        Create a new post
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <g:hasErrors bean="${postInstance}">
                    <g:eachError bean="${postInstance}" var="error">
                        <div class="alert alert-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
                            <g:message error="${error}"/>
                        </div>
                    </g:eachError>
                </g:hasErrors>

                <g:form url="[resource:postInstance, action:'save']" >
                    <g:render template="form"/>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/post/edit.gsp
<%@ page import="grailsblog.Post" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Edit post ${postInstance.title}</title>

        <link rel="stylesheet" href="${resource(dir: 'css', file: 'chosen.css')}" type="text/css">

        <script type="text/javascript" src="${resource(dir: 'js/tinymce/', file: 'tinymce.min.js')}"></script>
        <script src="${resource(dir: 'js', file: 'chosen.jquery.js')}"></script>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Edit user ${postInstance.title}</h1>

                <ol class="breadcrumb">
                    <li>
                        <g:link class="list" action="index">
                            <i class="fa fa-files-o"></i> Posts
                        </g:link>
                    </li>
                    <li class="active">
                        Edit user ${postInstance.title}
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <g:hasErrors bean="${postInstance}">
                    <g:eachError bean="${postInstance}" var="error">
                        <div class="alert alert-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
                            <g:message error="${error}"/>
                        </div>
                    </g:eachError>
                </g:hasErrors>

                <g:form url="[resource:postInstance, action:'update']" method="PUT" >
                    <g:render template="form"/>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/post/index.gsp
<%@ page import="grailsblog.Post" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Posts</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Posts</h1>

                <ol class="breadcrumb">
                    <li class="active">
                        <i class="fa fa-files-o"></i> Posts
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <p>
                    <a href="${ createLink(action: 'create') }" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Create a new post
                    </a>
                </p>

                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Slug</th>
                            </tr>
                        </thead>
                        <tbody>
                            <g:each in="${postInstanceList}" status="i" var="postInstance">
                                <tr>
                                    <td>
                                        <g:link action="edit" id="${postInstance.id}">
                                            ${postInstance.title}
                                        </g:link>
                                    </td>
                                    <td>
                                        ${postInstance.author.fullname}
                                    </td>
                                    <td>
                                        ${postInstance.slug}
                                    </td>
                                </tr>
                            </g:each>
                            <g:unless test="${postInstanceList}">
                                <tr>
                                    <td colspan="3">
                                        <p class="noRecord">No Posts Found!</p>
                                    </td>
                                </tr>
                            </g:unless>
                        </tbody>
                    </table>
                </div>

                <div class="pagination">
                    <g:paginate total="${postInstanceCount ?: 0}" controller="post" action="index" />
                </div>
            </div>
        </div>
    </body>
</html>

grails-app/views/post/list.gsp
<%@ page import="grailsblog.Post" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <title>Grailsblog</title>
    </head>
    <body>
        <g:each in="${postInstanceList}" status="i" var="postInstance">
            <article class="post_article">
                <h3 class="post_title">
                    <g:link action="show" params="[slug: postInstance.slug]">
                        ${ postInstance.title }
                    </g:link>
                </h3>
                <h6 class="post_date">
                     Posted on <g:formatDate format="MMMMM d, yyyy" date="${ postInstance.dateCreated }" />
                </h6>

                <div class="post_content">
                    ${ raw(postInstance.content) }
                </div>

                <div class="post_meta_info">
                    <p>Posted by: ${ postInstance.author.fullname }</p>
                    <p>
                        Category:
                        <g:each in="${postInstance.getCategories()}" status="cat_i" var="postCategory">
                            <g:link controller="category" action="list" params="[slug: postCategory.slug]">${postCategory.name}</g:link>${ (postInstance.getCategories().size() != (cat_i + 1) ) ? ', ' : ''}
                        </g:each>
                    </p>
                    <p>
                        Tags:
                        <g:each in="${postInstance.getTags()}" status="tag_i" var="postTag">
                            <g:link controller="tag" action="list" params="[slug: postTag.slug]">${postTag.name}</g:link>${ (postInstance.getTags().size() != (tag_i + 1) ) ? ', ' : ''}
                        </g:each>
                    </p>
                </div>
            </article>

            <g:if test="${postInstanceList.size() != (i+1)}">
                <hr>
                <br>
            </g:if>

            <div class="pagination">
                <g:paginate total="${postInstanceCount ?: 0}" controller="post" action="list" />
            </div>
        </g:each>
    </body>
</html>

grails-app/views/post/show.gsp
<%@ page import="grailsblog.Post" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <title>Grailsblog - ${postInstance.title}</title>
    </head>
    <body>
        <article class="post_article">
            <h3 class="post_title">
                <g:link action="show" params="[slug: postInstance.slug]">
                    ${ postInstance.title }
                </g:link>
            </h3>
            <h6 class="post_date">
                 Posted on <g:formatDate format="MMMMM d, yyyy" date="${ postInstance.dateCreated }" />
            </h6>

            <div class="post_content">
                ${ raw(postInstance.content) }
            </div>

            <div class="post_meta_info">
                <p>Posted by: ${ postInstance.author.fullname }</p>
                <p>
                    Category:
                    <g:each in="${postInstance.getCategories()}" status="cat_i" var="postCategory">
                        <g:link controller="category" action="list" params="[slug: postCategory.slug]">${postCategory.name}</g:link>${ (postInstance.getCategories().size() != (cat_i + 1) ) ? ', ' : ''}
                    </g:each>
                </p>
                <p>
                    Tags:
                    <g:each in="${postInstance.getTags()}" status="tag_i" var="postTag">
                        <g:link controller="tag" action="list" params="[slug: postTag.slug]">${postTag.name}</g:link>${ (postInstance.getTags().size() != (tag_i + 1) ) ? ', ' : ''}
                    </g:each>
                </p>
            </div>
        </article>
    </body>
</html>