grails-app/domain/grailsblog/SecUser.groovy
package grailsblog

class SecUser {

    transient springSecurityService

    String firstname
    String lastname
    String email
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired
    Date dateCreated
    Date lastUpdated

    static transients = ['springSecurityService']

    static hasMany = [posts: Post]

    static constraints = {
        firstname blank: false, maxSize: 50
        lastname blank: false, maxSize: 50
        email blank: false, unique: true, email: true
        password blank: false
    }

    static mapping = {
        password column: '`password`'
    }

    Set<SecRole> getAuthorities() {
        SecUserSecRole.findAllBySecUser(this).collect { it.secRole } as Set
    }

    def beforeInsert() {
        encodePassword()
    }

    def beforeUpdate() {
        if (isDirty('password')) {
            encodePassword()
        }
    }

    protected void encodePassword() {
        password = springSecurityService.encodePassword(password)
    }

    String getFullname() {
        return firstname.trim() + " " + lastname.trim()
    }
}

grails-app/controllers/grailsblog/SecUserController.groovy
package grailsblog



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class SecUserController {

    static allowedMethods = [save: "POST", update: "PUT"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond SecUser.list(params), model:[secUserInstanceCount: SecUser.count()]
    }

    def create() {
        respond new SecUser(params)
    }

    @Transactional
    def save(SecUser secUserInstance) {
        if (secUserInstance == null) {
            notFound()
            return
        }

        if (secUserInstance.hasErrors()) {
            respond secUserInstance.errors, view:'create'
            return
        }

        secUserInstance.save flush:true

        def authorRole = SecRole.findByAuthority('ROLE_AUTHOR') ?: new SecRole(authority: 'ROLE_AUTHOR').save(failOnError: true)

        if (!secUserInstance.authorities.contains(authorRole)) {
            SecUserSecRole.create secUserInstance, authorRole
        }

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'secUserInstance.label', default: 'User'), secUserInstance.fullname])
                redirect action:"index", method:"GET"
            }
            '*' { respond secUserInstance, [status: CREATED] }
        }
    }

    def edit(SecUser secUserInstance) {
        respond secUserInstance
    }

    @Transactional
    def update(SecUser secUserInstance) {
        if (secUserInstance == null) {
            notFound()
            return
        }

        if (secUserInstance.hasErrors()) {
            respond secUserInstance.errors, view:'edit'
            return
        }

        secUserInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'secUserInstance.label', default: 'User'), secUserInstance.fullname])
                redirect action: "index", method: "GET"
            }
            '*'{ respond secUserInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(SecUser secUserInstance) {

        if (secUserInstance == null) {
            notFound()
            return
        }

        SecUserSecRole.removeAll(secUserInstance)

        secUserInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'secUserInstance.label', default: 'User'), secUserInstance.fullname])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'secUserInstance.label', default: 'SecUser'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/secUser/_form.gsp
<%@ page import="grailsblog.SecUser" %>
<div class="form-group">
    <label for="firstname">Firstname <span class="required-indicator">*</span></label>
    <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Enter firstname" value="${secUserInstance?.firstname}" required="">
</div>

<div class="form-group">
    <label for="lastname">Lastname <span class="required-indicator">*</span></label>
    <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Enter lastname" value="${secUserInstance?.lastname}" required="">
</div>

<div class="form-group">
    <label for="email">Email <span class="required-indicator">*</span></label>
    <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address" value="${secUserInstance?.email}" required="">
</div>

<g:if test="${secUserInstance.id}">
    <div class="form-group">
        <label for="enabled">
            Is Enabled
            <g:checkBox name="enabled" value="${secUserInstance?.enabled}" />
        </label>
    </div>

    <div  class="form-group">
        <label for="changepass">
            Change Password
            <input id="changepass" type="checkbox">
        </label>
    </div>

    <div id="passwordFormGroup" class="form-group" style="display:none;">
        <label for="password">Password <span class="required-indicator">*</span></label>
        <input type="password" class="form-control" id="password" name="changepass" placeholder="Enter the password" value="">
    </div>
</g:if>
<g:else>
    <div class="form-group">
        <label for="password">Password <span class="required-indicator">*</span></label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" value="" required="">
    </div>
</g:else>

<div class="form-group">
    <g:if test="${secUserInstance.id}">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Update user
        </button>
        or
        <a href="${ createLink(controller: 'secUser', action: 'delete', id: secUserInstance.id) }" class="btn btn-danger" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
            <i class="fa fa-trash-o"></i> Delete user
        </a>
    </g:if>
    <g:else>
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i> Create user
        </button>
    </g:else>
    or
    <a href="${ createLink(controller: 'secUser', action: 'index') }">Cancel</a>
</div>


<g:if test="${secUserInstance.id}">
    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery('#changepass').change(function() {
                if (jQuery(this).is(':checked')) {
                    jQuery('#passwordFormGroup').show();
                    jQuery('#password').attr('name', 'password');
                    jQuery('#password').attr('required', 'required');
                } else {
                    jQuery('#passwordFormGroup').hide();
                    jQuery('#password').attr('name', 'changepass');
                    jQuery('#password').removeAttr('required');
                }
            });
        });
    </script>
</g:if>

grails-app/views/secUser/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Create a new user</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Create a new user</h1>

                <ol class="breadcrumb">
                    <li>
                        <g:link class="list" action="index">
                            <i class="fa fa-user"></i> Users
                        </g:link>
                    </li>
                    <li class="active">
                        Create a new user
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <g:hasErrors bean="${secUserInstance}">
                    <g:eachError bean="${secUserInstance}" var="error">
                        <div class="alert alert-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
                            <g:message error="${error}"/>
                        </div>
                    </g:eachError>
                </g:hasErrors>

                <g:form url="[resource:secUserInstance, action:'save']" >
                    <g:render template="form"/>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/secUser/edit.gsp
<%@ page import="grailsblog.SecUser" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Edit user ${secUserInstance.fullname}</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Edit user ${secUserInstance.fullname}</h1>

                <ol class="breadcrumb">
                    <li>
                        <g:link class="list" action="index">
                            <i class="fa fa-user"></i> Users
                        </g:link>
                    </li>
                    <li class="active">
                        Edit user ${secUserInstance.fullname}
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <g:hasErrors bean="${secUserInstance}">
                    <g:eachError bean="${secUserInstance}" var="error">
                        <div class="alert alert-danger" <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>>
                            <g:message error="${error}"/>
                        </div>
                    </g:eachError>
                </g:hasErrors>

                <g:form url="[resource:secUserInstance, action:'update']" method="PUT" >
                    <g:render template="form"/>
                </g:form>
            </div>
        </div>
    </body>
</html>

grails-app/views/secUser/index.gsp
<%@ page import="grailsblog.SecUser" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="admin">
        <title>Grailsblog - Users</title>
    </head>
    <body>
        <div class="row">
            <div class="col-lg-12">
                <h1>Users</h1>

                <ol class="breadcrumb">
                    <li class="active">
                        <i class="fa fa-user"></i> Users
                    </li>
                </ol>

                <g:if test="${flash.message}">
                    <div class="alert alert-info">
                        ${flash.message}
                    </div>
                </g:if>

                <p>
                    <a href="${ createLink(action: 'create') }" class="btn btn-primary">
                        <i class="fa fa-plus"></i> Create a new user
                    </a>
                </p>

                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped">
                        <thead>
                            <tr>
                                <th>Fullname</th>
                                <th>Email</th>
                                <th>Is Active?</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <g:each in="${secUserInstanceList}" status="i" var="secUserInstance">
                                <tr>
                                    <td>
                                        ${fieldValue(bean: secUserInstance, field: "fullname")}
                                    </td>
                                    <td>
                                        ${fieldValue(bean: secUserInstance, field: "email")}
                                    </td>
                                    <td>
                                        <g:formatBoolean boolean="${secUserInstance.enabled}" true="Yes" false="No" />
                                    </td>
                                    <td>
                                        <g:link action="edit" id="${secUserInstance.id}">
                                            Edit
                                        </g:link>
                                    </td>
                                </tr>
                            </g:each>
                        </tbody>
                    </table>
                </div>

                <div class="pagination">
                    <g:paginate total="${secUserInstanceCount ?: 0}" />
                </div>
            </div>
        </div>
    </body>
</html>